server:
  port: '9000'
  servlet:
    context-path: /api/v1

spring:
  datasource:
    username: book_corner
    password: book_corner
    url: jdbc:postgresql://localhost:5432/book_corner
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db.changelog/changelog-master.yaml